version: '3'
services:
  app:
    build: ./app/.
    stdin_open: true
    tty: true
    ports:
     - "80:8080"
    volumes:
     - ./app/src:/src
    networks:
     - net

  db:
   build: ./db/.
   environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=project-db
    - MYSQL_USER=user
    - MYSQL_PASSWORD=secret
   networks:
    - net

networks:
  net:

   
