FROM mysql:5.7.24
MAINTAINER Charalambos Paschalides "already.late@gmail.com"

# Create a volume at the container's /var/lib/mysql directory. This directory
# will therefore bypass the Union File System so the host and other containers
# can mount it.
VOLUME /var/lib/mysql
